library("ape")
setwd("/Users/sunlinhua/Downloads/10-31/name_changed/")
pdf(file = "2015_11_3_ML.pdf",height = 8,width = 20)
MLfiles<-dir(pattern = "raxml_speciestrees.tre$")
par(mfrow=c(2,5))
for (i in MLfiles)  {
  tree1<-read.tree(i)
  tree1$tip.label<-gsub("_","\ ",tree1$tip.label)
  tree1$node.label<-round(as.numeric(tree1$node.label))
  plot(tree1,use.edge.length=FALSE,cex=0.8,font=3,main=i )
  nodelabels(tree1$node.label,adj = -0.1,frame="none",cex=0.5,font=2)
}
dev.off()
pdf(file = "2015_11_3_bayes.pdf",height = 8,width = 20)
bayesfiles<-dir(pattern = "^bayes_")
par(mfrow=c(2,5))
for (i in bayesfiles)  {
  tree1<-read.tree(i)
  tree1$tip.label<-gsub("_","\ ",tree1$tip.label)
  tree1$node.label<-round(as.numeric(tree1$node.label))
  plot(tree1,use.edge.length=FALSE,cex=0.8,font=3,main=i,root.edge=T)
  nodelabels(tree1$node.label,adj = -0.1,frame="none",cex=0.5,font=2)
}
dev.off()
#tretry<-read.tree("name_changed_10_raxml_speciestrees.tre")
#tretry$tip.label<-gsub("_","\ ",tretry$tip.label)
#plot(tretry,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tretry$node.label#,adj = 0,frame="none",cex=0.4,font=2)
#
#tree1<-read.tree("1_raxml_speciestrees.tre")
#tree1$tip.label<-gsub("_","\ ",tree1$tip.label)
#plot(tree1,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tree1$node.label,adj= -0.1#,frame="none",cex=0.4,font=2)
#tree2<-read.tree("name_changed_2_raxml_speciestrees.tre")
#tree2$tip.label<-gsub("_","\ ",tree2$tip.label)
#tree3<-read.tree("name_changed_3_raxml_speciestrees.tre")
#tree3$tip.label<-gsub("_","\ ",tree3$tip.label)
#tree4<-read.tree("name_changed_4_raxml_speciestrees.tre")
#tree4$tip.label<-gsub("_","\ ",tree4$tip.label)
#tree5<-read.tree("name_changed_5_raxml_speciestrees.tre")
#tree5$tip.label<-gsub("_","\ ",tree5$tip.label)
#tree6<-read.tree("name_changed_6_raxml_speciestrees.tre")
#tree6$tip.label<-gsub("_","\ ",tree6$tip.label)
#tree7<-read.tree("name_changed_7_raxml_speciestrees.tre")
#tree7$tip.label<-gsub("_","\ ",tree7$tip.label)
#tree8<-read.tree("name_changed_8_raxml_speciestrees.tre")
#tree8$tip.label<-gsub("_","\ ",tree8$tip.label)
#tree9<-read.tree("name_changed_9_raxml_speciestrees.tre")
#tree9$tip.label<-gsub("_","\ ",tree9$tip.label)
#tree10<-read.tree("name_changed_10_raxml_speciestrees.tre")
#tree10$tip.label<-gsub("_","\ ",tree10$tip.label)
#plot(tree1,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tree1$node.label,adj #= 0,frame="none",cex=0.4,font=2)
#plot(tree2,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tree2$node.label,adj #= 0,frame="none",cex=0.4,font=2)
#plot(tree3,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tree3$node.label,adj #= 0,frame="none",cex=0.4,font=2)
#plot(tree4,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tree4$node.label,adj #= 0,frame="none",cex=0.4,font=2)
#plot(tree5,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tree5$node.label,adj #= 0,frame="none",cex=0.4,font=2)
#plot(tree6,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tree6$node.label,adj #= 0,frame="none",cex=0.4,font=2)
#plot(tree7,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tree7$node.label,adj #= 0,frame="none",cex=0.4,font=2)
#plot(tree8,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tree8$node.label,adj #= 0,frame="none",cex=0.4,font=2)
#plot(tree9,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tree9$node.label,adj #= 0,frame="none",cex=0.4,font=2)
#plot(tree10,use.edge.length=FALSE,cex=0.8,font=3);nodelabels(tree10$node.label#,adj = 0,frame="none",cex=0.4,font=2)



#nodelabels(tretry)
#
#ggtree(tretry, color="black", branch.length='none',size=0.5)%>% #add_legend()+geom_text(aes(label=label), size=2,hjust=-0.05)
#
#grid.arrange(ggtree(tretry, color="black", size=0.5)%>% add_legend#()+geom_text(aes(label=label), size=4,  hjust=-0.05),ggtree(tretry, #color="black", size=0.5)%>% add_legend()+geom_text(aes(label=label), #size=4,  hjust=-0.05),ncol=2)
#
#unrooted_tretry<-(unroot(tretry))
#rerooted_tretry<-root(unrooted_tretry,node = 16,resolve.root = TRUE )